import tkinter as tk

class Battery_Image(object):
    def __init__(self, root):
        self._root = root
        self._top_border = tk.Frame(self._root, relief=tk.GROOVE, border=1)
        self._bottom_border = tk.Frame(self._root, relief=tk.GROOVE, border=1)
        self._battery_cell_0 = tk.Frame(self._top_border)
        self._battery_cell_1 = tk.Frame(self._bottom_border)
        self._battery_cell_2 = tk.Frame(self._bottom_border)
        self._battery_cell_3 = tk.Frame(self._bottom_border)
        self._battery_cell_4 = tk.Frame(self._bottom_border)
        self._battery_cell_5 = tk.Frame(self._bottom_border)
        self._battery_cell_6 = tk.Frame(self._bottom_border)
        self._battery_cell_7 = tk.Frame(self._bottom_border)
        self._battery_cell_8 = tk.Frame(self._bottom_border)
        self._battery_cell_9 = tk.Frame(self._bottom_border)
        self.setSize()
        self.setGrid()

    def setSize(self):
        self._battery_cell_0.configure(height=15, width=30)
        self._battery_cell_1.configure(height=15, width=70)
        self._battery_cell_2.configure(height=15, width=70)
        self._battery_cell_3.configure(height=15, width=70)
        self._battery_cell_4.configure(height=15, width=70)
        self._battery_cell_5.configure(height=15, width=70)
        self._battery_cell_6.configure(height=15, width=70)
        self._battery_cell_7.configure(height=15, width=70)
        self._battery_cell_8.configure(height=15, width=70)
        self._battery_cell_9.configure(height=15, width=70)

    def interfaceBypassGrid(self):
        self._battery_cell_0.configure(height=25, width=30)
        self._top_border.grid(row=0, column=2, rowspan=3, padx=15, pady=20)

    def interfaceAutoGrid(self):
        self._battery_cell_0.configure(height=15, width=30)
        self._top_border.grid(row=0, column=2, rowspan=1, padx=20)

    def setGrid(self):
        self._battery_cell_0.grid(row=0, column=2)
        self._battery_cell_1.grid(row=1, column=2)
        self._battery_cell_2.grid(row=2, column=2)
        self._battery_cell_3.grid(row=3, column=2)
        self._battery_cell_4.grid(row=4, column=2)
        self._battery_cell_5.grid(row=5, column=2)
        self._battery_cell_6.grid(row=6, column=2)
        self._battery_cell_7.grid(row=7, column=2)
        self._battery_cell_8.grid(row=8, column=2)
        self._battery_cell_9.grid(row=9, column=2)
        self._top_border.grid(row=0, column=2, padx=20)
        self._bottom_border.grid(row=0, column=2, rowspan=10, pady=32, padx=20)

    def setCells(self, level):
        if (level >= 95):
            self._battery_cell_0.configure(background="lime")
            self._battery_cell_1.configure(background="lime")
            self._battery_cell_2.configure(background="lime")
            self._battery_cell_3.configure(background="lime")
            self._battery_cell_4.configure(background="lime")
            self._battery_cell_5.configure(background="lime")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 95 and level >= 85):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="lime")
            self._battery_cell_2.configure(background="lime")
            self._battery_cell_3.configure(background="lime")
            self._battery_cell_4.configure(background="lime")
            self._battery_cell_5.configure(background="lime")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 85 and level >= 75):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="lime")
            self._battery_cell_3.configure(background="lime")
            self._battery_cell_4.configure(background="lime")
            self._battery_cell_5.configure(background="lime")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 75 and level >= 65):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="lime")
            self._battery_cell_4.configure(background="lime")
            self._battery_cell_5.configure(background="lime")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 65 and level >= 55):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="white")
            self._battery_cell_4.configure(background="lime")
            self._battery_cell_5.configure(background="lime")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 55 and level >= 45):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="white")
            self._battery_cell_4.configure(background="white")
            self._battery_cell_5.configure(background="lime")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 45 and level >= 35):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="white")
            self._battery_cell_4.configure(background="white")
            self._battery_cell_5.configure(background="white")
            self._battery_cell_6.configure(background="lime")
            self._battery_cell_7.configure(background="lime")
            self._battery_cell_8.configure(background="lime")
            self._battery_cell_9.configure(background="lime")
        elif (level < 35 and level >= 25):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="white")
            self._battery_cell_4.configure(background="white")
            self._battery_cell_5.configure(background="white")
            self._battery_cell_6.configure(background="white")
            self._battery_cell_7.configure(background="yellow")
            self._battery_cell_8.configure(background="yellow")
            self._battery_cell_9.configure(background="yellow")
        elif (level < 25 and level >= 15):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="white")
            self._battery_cell_4.configure(background="white")
            self._battery_cell_5.configure(background="white")
            self._battery_cell_6.configure(background="white")
            self._battery_cell_7.configure(background="white")
            self._battery_cell_8.configure(background="yellow")
            self._battery_cell_9.configure(background="yellow")
        elif (level < 15 and level >= 00):
            self._battery_cell_0.configure(background="white")
            self._battery_cell_1.configure(background="white")
            self._battery_cell_2.configure(background="white")
            self._battery_cell_3.configure(background="white")
            self._battery_cell_4.configure(background="white")
            self._battery_cell_5.configure(background="white")
            self._battery_cell_6.configure(background="white")
            self._battery_cell_7.configure(background="white")
            self._battery_cell_8.configure(background="white")
            self._battery_cell_9.configure(background="red")


